const assert=require('node:assert/strict');
const core=require('../memex/study-core.js');
const source='The area of a rectangle equals its length multiplied by its width.';
const p={difficulty:'Advanced',technical:'technical',format:'mcq',count:1,inputType:'text'};
const q={id:'q1',prompt:'Which proposed area calculation is valid?',format:'mcq',options:['12','7','5','24'],answer:'12',explanation:'Multiply 3 by 4.',bloom:'Analyze',sourceQuote:source,concept:'Area of rectangles'};
const review={verdicts:[{id:'q1',valid:true,reason:'The multiplication and dimensions are supported.'}]};
const check=(question=q,verification=review,params=p)=>core.validate({questions:[question]},verification,params,source).questions.length;
assert.equal(check(),1);
assert.equal(check({...q,sourceQuote:'This quotation was invented.'}),0);
assert.equal(check(q,{verdicts:[{id:'q1',valid:false,reason:'Incorrect calculation'}]}),0);
assert.equal(check(q,{verdicts:[]}),0);
assert.equal(check(q,{verdicts:[...review.verdicts,...review.verdicts]}),0);
assert.equal(check({...q,answer:'100'}),0);
assert.equal(check({...q,options:['12','12','5','24']}),0);
assert.equal(check({...q,bloom:'Remember'}),0);
assert.equal(check({...q,format:'short'}),0);
assert.equal(check(q,review,{...p,inputType:'seed'}),0);
assert.equal(check({...q,abstractRule:'A = l*w',variation:'New dimensions and scenario'},review,{...p,inputType:'seed'}),1);
assert.deepEqual(core.levels({...p,difficulty:'Foundation',technical:'conceptual'}),['Remember','Understand']);
assert.match(core.generation({...p,inputType:'seed'},source,'seed'),/THEN express an abstract/);
assert.match(core.verification(p,source,{questions:[q]}),/Independently solve/);
console.log('PASS: source matching, rejection and missing verdicts, duplicate verdicts/options, answer membership, Bloom constraints, seed abstraction.');
